#!/bin/sh

if [ "`which python3`" = /usr/bin/python3 ]
then
    echo "Activating venv"
    . .venv/bin/activate
fi

sudo mkdir -v /run/startpg
sudo chown -c /run/startpg --reference=$0

flask --app face.face run --host 0.0.0.0 --debug
