#!/bin/sh

if [ "`which python3`" = /usr/bin/python3 ]
then
    echo "Activating venv"
    . .venv/bin/activate
fi

sudo mkdir -v /run/startpg
sudo chown -c /run/startpg --reference=$0

# Localhost only: --debug serves Flask's interactive debugger.
flask --app face.face run --debug
