#!/bin/bash
# The start page init script

me=`basename $0`

start_dir="/root/startpg"
debug_dir="/home/mrc/code/startpg"
start_cmd="python3 start.py"

is_running() {
  ps aux|grep -v grep|grep -q "$start_cmd"
}

get_pid() {
  ps aux|grep -v grep|grep "$start_cmd"|awk '{print $2}'
}

case $1 in
  start)
    if is_running
    then
      echo "$me is already running!"
      exit 1
    fi
    if ! cd $start_dir >/dev/null 2>&1
    then
      echo "starting debug session"
      if ! cd $debug_dir >/dev/null 2>&1
      then
        echo "I have no idea where you are, this isn't going to work until you edit code dude"
        exit 1
      fi
    fi
    $start_cmd >/var/log/startpg.log 2>&1 &
  ;;
  stop)
    kill `get_pid`
  ;;
  restart)
    $0 stop
    sleep 1
    $0 start
  ;;
  status)
    if ! is_running
    then
      echo -n 'not '
    fi
    echo 'running'
  ;;
  *)
    echo "usage: $me {start|stop|restart|status}"
    exit 1
  ;;
esac

