#!/bin/bash
# The start page init script

me=`basename $0`

start_dir="/root/startpg"
start_cmd="python start.py"

is_running() {
  ps aux|grep -v grep|grep -q $start_cmd
}

get_pid() {
  ps aux|grep -v grep|grep "$start_cmd"|awk '{print $2}'
}

case $1 in
  start)
    if is_running
    then
      echo "$me is already running!"
      exit 1
    fi
    cd $start_dir
    $start_cmd >/var/log/startpg.log 2>&1 &
  ;;
  stop)
    kill `get_pid`
  ;;
  restart)
    $0 stop
    sleep 1
    $0 start
  ;;
  status)
    if ! is_running
    then
      echo -n 'not '
    fi
    echo 'running'
  ;;
  *)
    echo "usage: $me {start|stop|restart|status}"
  ;;
esac

